import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import * as PIXI from 'pixi.js'
import { ICanvas } from 'pixi.js';


const SAMPLE_DATA_LIST = [
  {
    id: 1,
    name: 'sample1',
    src: 'https://picsum.photos/id/737/600/420'
  },
  {
    id: 2,
    name: 'sample2',
    src: 'https://picsum.photos/id/837/600/420'
  },
  {
    id: 3,
    name: 'sample3',
    src: 'https://picsum.photos/id/547/600/420'
  },
];

export default function Home() {
  const onLoad = (element: HTMLElement) => {
    if (!element) return

    const app = new PIXI.Application({
      width: window.innerWidth,
      height: 2400, // TODO: 下側を固定値差し引く
      backgroundColor: 0x1099bb,
      resolution: window.devicePixelRatio || 1,
      antialias: true,
      backgroundAlpha: 0, // デフォルトは透過させない
      resizeTo: window,
      view: document.querySelector('canvas') as ICanvas,
    });

    app.renderer.plugins.interaction.autoPreventDefault = false;

    const imageListContainer = new PIXI.Container();
    app.stage.addChild(imageListContainer);

    SAMPLE_DATA_LIST.map((data, i) => {
      const imageSprite = PIXI.Sprite.from(data.src);
      imageSprite.width = 300;
      imageSprite.height = 210;

      imageSprite.position.x = (i % 2) * 200;
      imageSprite.position.y = i * 300;
      imageListContainer.addChild(imageSprite);
    })

    element.appendChild(app.view);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.section} ref={onLoad} />
      </main>
    </>
  )
}
